apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: demo-app 
  name: demo-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      run: demo-app
  template: 
    metadata:
      labels:
        run: demo-app 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
