apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gamestore
  labels:
    run: demo-app 
  name: demo-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-app
  template: 
    metadata:
      labels:
        run: demo-app 
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 80
          protocol: TCP